# Generated by Django 4.2.1 on 2023-06-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aspra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('tamaño', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('fecha_ingreso', models.DateTimeField()),
                ('id_refufio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspra.refugio')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspra.tipoanimal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'Animales',
            },
        ),
    ]
