# Generated by Django 4.2.1 on 2023-05-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aspra', '0002_donacion_refugio_veterinarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veterinarios',
            new_name='Veterinario',
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'verbose_name': 'Donacion', 'verbose_name_plural': 'Donaciones'},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'verbose_name': 'Veterinario', 'verbose_name_plural': 'Veterinarios'},
        ),
        migrations.RenameField(
            model_name='veterinario',
            old_name='email_veterinario',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='veterinario',
            old_name='nombre_veterinario',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='veterinario',
            old_name='telefono_veterinario',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='dni_usuario3',
        ),
        migrations.AlterModelTable(
            name='donacion',
            table='Donacion',
        ),
        migrations.AlterModelTable(
            name='veterinario',
            table='Veterinario',
        ),
    ]
