# Generated by Django 4.2.1 on 2023-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspra', '0002_animales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
