# Generated by Django 4.2.1 on 2023-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspra', '0003_rename_veterinarios_veterinario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAnimales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'UsuarioAnimales',
                'verbose_name_plural': 'UsuarioAnimales',
                'db_table': 'UsuarioAnimales',
            },
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='id_donacion',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='refugio',
            old_name='id_refugio',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='id_reporte',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='id',
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='matricula',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
