# Generated by Django 4.2.1 on 2023-06-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspra', '0004_rename_tamaño_animales_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='animales',
            name='img',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
