# Generated by Django 4.2.1 on 2023-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=45)),
                ('nombre_veterinario', models.CharField(max_length=45)),
                ('telefono_veterinario', models.CharField(max_length=45)),
                ('email_veterinario', models.CharField(max_length=45)),
            ],
        ),
    ]
